// WhatsApp Cloud API adapter (Meta).
// This is a real integration against Meta's official WhatsApp Business
// Cloud API — not a mock. To actually send messages, set these in .env:
//   WHATSAPP_TOKEN=<permanent access token from Meta Business Suite>
//   WHATSAPP_PHONE_NUMBER_ID=<your WhatsApp Business phone number ID>
//
// Docs: https://developers.facebook.com/docs/whatsapp/cloud-api
// Getting these requires a Meta Business account + WhatsApp Business
// verification — that step has to happen on your side; it can't be
// generated by code.

async function sendWhatsAppMessage(toPhoneNumber, text) {
  const token = process.env.WHATSAPP_TOKEN;
  const phoneNumberId = process.env.WHATSAPP_PHONE_NUMBER_ID;

  if (!token || !phoneNumberId) {
    throw new Error(
      'WhatsApp not configured yet. Set WHATSAPP_TOKEN and WHATSAPP_PHONE_NUMBER_ID in .env ' +
      '(from Meta Business Suite) to enable sending.'
    );
  }

  const url = `https://graph.facebook.com/v20.0/${phoneNumberId}/messages`;
  const response = await fetch(url, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      messaging_product: 'whatsapp',
      to: toPhoneNumber,
      type: 'text',
      text: { body: text },
    }),
  });

  const data = await response.json();
  if (!response.ok) {
    throw new Error(`WhatsApp send failed: ${JSON.stringify(data)}`);
  }
  return data;
}

module.exports = { sendWhatsAppMessage };
